language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
#  - clang
  
before_install:
  - pip install --user cpp-coveralls

install:
    - cd ${TRAVIS_BUILD_DIR}
    - pwd
    - ./scripts/install_coverage.sh

before_script:
    - cd ${TRAVIS_BUILD_DIR}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake .
    - make
    - ctest --verbose

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - pwd
    - ./scripts/finish_coverage.sh

