language: cpp

sudo: required

matrix:
  fast_finish: true
  include:
  - os: linux
    env: DOCUMENTATION=ON
    addons:
      apt:
        packages:
        - xsltproc
  - os: linux
    env: TOOLSET=clang CXX=clang++
    addons:
      apt:
        packages:
        - xsltproc
  - os: linux
    env: CLANG_FORMAT=clang-format-3.8 CLANG_TIDY=clang-tidy-3.8
    addons:
      apt:
        packages:
        - clang-3.8
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise
  - os: linux
    env: TOOLSET=clang MEMCHECK=VALGRIND BENCHMARK=QUICK CXX=clang++-3.7
    addons:
      apt:
        packages:
        - clang-3.7
        - libstdc++-5-dev
        - valgrind
        - gdb
        - bc
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
  - os: osx
    osx_image: xcode6.1
    env: TOOLSET=clang CXX=clang++
  
notifications:
  email:
    on_success: never

#compiler:
#  - gcc
#  - clang
  
before_install:
# upgrade clang
#  - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test' -y;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' -y ;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get update;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ];                        then sudo apt-get install -qq g++-4.9;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.9  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-4.9  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ];     then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-get install clang-3.7;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang  clang  /usr/bin/clang-3.7  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++  clang++  /usr/bin/clang++-3.7  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.7 | head -1);sudo ln -s ${a} /usr/bin/llvm-cov;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then a=$(sudo find / -name llvm-cov | grep 3.4 | head -1);sudo mv ${a} ${a}.old;fi
#
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' --yes ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-add-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'  --yes; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-get update ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang  clang  /usr/bin/clang-3.7  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++  clang++  /usr/bin/clang++-3.7  90;fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.7; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "clang++" ]; then export CXX="clang-3.7" CC="clang-3.7"; fi
  - clang --version
#  - sudo apt-get install libclang1-3.7 libclang-common-3.7-dev  --yes --force-yes
# - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-3.7.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
# - sudo ldconfig  
  
# c++ coveralls install
  - pip install --user cpp-coveralls
  
install:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake .
    - pwd
    - chmod a+x ./scripts/*.sh
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ]; then ./scripts/install_coverage.sh; fi

before_script:
    - cd ${TRAVIS_BUILD_DIR}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make
    - ctest --verbose

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - pwd
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" == "g++" ]; then ./scripts/finish_coverage.sh; fi
    - rm -rf clang-tidy-warnings.txt
    - clang-tidy -checks='*,-google-*,-misc-macro-parentheses,-readability-braces-around-statements,-readability-named-parameter,-llvm-namespace-comment' -header-filter='framework/[^/]*.h' -- -DNDEBUG -std=c++11 -I. -Iframework > clang-tidy-warnings.txt
    - cat clang-tidy-warnings.txt
    - if [ -s clang-tidy-warnings.txt ]; then exit 1; fi
    - ls /usr/local
#    - /usr/share/clang/scan-build-3.8/scan-build --use-analyzer=/usr/bin/clang-3.8 -o "$REPORTS" ./b2 toolset=gcc-4.8 libs/afio/test -a --test=test_all.cpp --link-test

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Nn/0vOtTfb5ETN6uN8hA6MiKYAYCIGJ6WJwKL+5inRp8jMe9VjeZqHHgQPGB4IM/ryBEJtGJF8grykkjx2WPFI4vTkVWiAVQD8Hk4iVcdDHffk+Z5SNGE+y8ex8WCzHKdsa36y1m2FTCtnYtH2Wl37E5gXlCL2kMrEz3F9FA+icHsMDt+U1TodXtApd1kW5OyLxlrbTqGy7bx61vgnxU86a+QDpfaycnfX1H564M00nlLOPq2rIkYIxVgxoZ72ruTW/pJ+dOaHvIdJ5OMaR0uxIE7rT0utgWXMfOkG0EN8lDrRptvxpRktTRVHbU9h3JqKCCU0hQF2NgAJR8fKfHxxuinuuGHADOSoMruTI6UUT6U+mVwGlccH562rYFfEGI60882OSvttBIW4P0zvx7eZAWPKtesmwuXIlMeYmJwI4iNnSJsa6qokfm+f9OGyeU4PjZBK1Q60BYxTFQPSqwlmUmN2VspGaK26RI3fVapOOOA6LgprqyHpt7iVW+mrI/d2PJ9IYPqUT17N1qTP5e6o3g6sgzOXTpKonsVbTZMn9eYkASZ8YQ1ZdOgowCVmwcbAivbcYatascGMRyypa03cuNCY8L8AYtl05e+y69KkTl9sPHM7kckvqh2s+8xLaSlUBNF2HIqa6yqZ8uRehTCblQlBlZXRWnpTIrjfoTSVE="

addons:
  coverity_scan:
    project:
      name: "mydeveloperday/cpp-net-framework"
      description: "Build submitted via Travis CI"
    notification_email: mydeveloperday@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan


