language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - ctest -VV
  - chmod a+rx ./scripts/generate_coverage.sh

