language: cpp

sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
#  - clang
  
before_install:
  - pip install --user cpp-coveralls

install:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake .
    - pwd
    - chmod a+x ./scripts/*.sh
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./scripts/install_coverage.sh; fi

before_script:
    - cd ${TRAVIS_BUILD_DIR}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make
    - ctest --verbose

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - pwd
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./scripts/finish_coverage.sh; fi

