install:
  - mkdir build
  - cd build
  - cmake ..
  - dir
  
platform:
  - x86
  - x64
  
configuration:
  - Debug
  - Release
  
build:
  project: cpp-net-framework.sln
  verbosity: detailed
  
test_script:
  - echo "Running Tests"
  - ctest -VV
